blank_lines_upper_bound = 3
brace_style = "PreferSameLine"
comment_width = 100
fn_args_layout = "Compressed"
group_imports = "StdExternalCrate"
imports_granularity = "Module"
inline_attribute_width = 40
match_block_trailing_comma = true
max_width = 120
overflow_delimited_expr = true
reorder_impl_items = true
tab_spaces = 2
trailing_comma = "Never"
unstable_features = true
use_field_init_shorthand = true
where_single_line = true
